spring:
  application:
    name: lets-play

security:
  jwt:
    secret: "LetsPlay_JWT_Secret_9fA3xQ7M2PZLwRk8eD5VJcB4HnS6Y0T"
    expiration-ms: 3600000

app:
  seed-admin:
    username: admin
    password: admin123
