spring:
  application:
    name: lets-play

security:
  jwt:
    secret: "SOUFIANsoufianSOUFIANsoufianSOUFIANsoufianSOUFIANsoufian"
    expiration-ms: 3600000

app:
  seed-admin:
    username: admin
    password: admin123
